#!/usr/bin/env bash
set -euo pipefail

OUTPUT=""
INPUT=""
TOPIC=""
SLIDES="8"
TITLE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT="$2"; shift 2 ;;
    --input) INPUT="$2"; shift 2 ;;
    --topic) TOPIC="$2"; shift 2 ;;
    --slides) SLIDES="$2"; shift 2 ;;
    --title) TITLE="$2"; shift 2 ;;
    *) echo "{\"error\":\"Unknown flag: $1\"}"; exit 1 ;;
  esac
done

if [[ -z "$OUTPUT" ]]; then
  echo '{"error":"--output <file.pptx> is required"}'
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VENV_DIR="$WORKSPACE_ROOT/.pptx-venv"
if [[ ! -x "$VENV_DIR/bin/python" ]]; then
  python3 -m venv "$VENV_DIR" >/dev/null 2>&1
  "$VENV_DIR/bin/pip" install --quiet python-pptx >/dev/null 2>&1
fi
PYTHON_BIN="$VENV_DIR/bin/python"
"$PYTHON_BIN" -c "import pptx" >/dev/null 2>&1 || {
  "$VENV_DIR/bin/pip" install --quiet python-pptx >/dev/null 2>&1
}

mkdir -p "$(dirname "$OUTPUT")"

if [[ -n "$INPUT" ]]; then
  JSON_DATA="$(cat "$INPUT")"
elif [[ -t 0 ]]; then
  JSON_DATA=""
else
  JSON_DATA="$(cat)"
fi

"$PYTHON_BIN" - "$OUTPUT" "$TOPIC" "$SLIDES" "$TITLE" "$JSON_DATA" << 'PYEOF'
import json
import os
import sys
from pathlib import Path

output, topic, slides_count, title_override, json_data = sys.argv[1:6]
slides_count = int(slides_count or "8")

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
except Exception as e:
    print(json.dumps({"error": f"python-pptx unavailable: {e}"}))
    raise SystemExit(1)


def add_title_slide(prs, title, subtitle=""):
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = subtitle


def add_bullets_slide(prs, title, bullets):
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = title
    tf = slide.shapes.placeholders[1].text_frame
    tf.clear()
    if not bullets:
        bullets = ["TBD"]
    for i, b in enumerate(bullets):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = str(b)
        p.level = 0
        p.font.size = Pt(20)


def add_image_slide(prs, title, image_path, caption=""):
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = title
    if image_path and os.path.exists(image_path):
        slide.shapes.add_picture(image_path, Inches(1.0), Inches(1.4), width=Inches(11.3))
    if caption:
        box = slide.shapes.add_textbox(Inches(1.0), Inches(6.9), Inches(11.0), Inches(0.5))
        box.text_frame.text = caption


def quick_outline(topic_text, n):
    base = topic_text or "Project Update"
    return {
        "title": title_override or base,
        "subtitle": "Generated by BuildAI",
        "slides": [
            {"title": "Agenda", "bullets": ["Overview", "Current status", "Risks", "Next steps"]},
            {"title": "Current Status", "bullets": ["What has been completed", "What is in progress", "Key metrics"]},
            {"title": "Risks & Blockers", "bullets": ["Top 3 risks", "Mitigation actions", "Owner assignments"]},
            {"title": "Timeline", "bullets": ["Milestones achieved", "Upcoming milestones", "Critical dates"]},
            {"title": "Financial Snapshot", "bullets": ["Budget vs actual", "Forecast", "Variance drivers"]},
            {"title": "Decisions Needed", "bullets": ["Open decisions", "Tradeoffs", "Recommended option"]},
            {"title": "Next 30 Days", "bullets": ["Execution plan", "Dependencies", "Success criteria"]},
            {"title": "Q&A", "bullets": ["Questions", "Feedback", "Follow-ups"]},
        ][: max(2, n)],
    }

payload = None
if json_data.strip():
    try:
        payload = json.loads(json_data)
    except Exception as e:
        print(json.dumps({"error": f"Invalid JSON input: {e}"}))
        raise SystemExit(1)

if not isinstance(payload, dict):
    payload = quick_outline(topic, slides_count)

if "slides" not in payload or not isinstance(payload.get("slides"), list):
    payload = quick_outline(topic, slides_count)

prs = Presentation()

deck_title = title_override or payload.get("title") or topic or "BuildAI Deck"
subtitle = payload.get("subtitle", "")
add_title_slide(prs, deck_title, subtitle)

for s in payload.get("slides", []):
    st = s.get("title", "Slide") if isinstance(s, dict) else "Slide"
    if isinstance(s, dict) and s.get("image"):
        add_image_slide(prs, st, s.get("image"), s.get("caption", ""))
    else:
        bullets = s.get("bullets", []) if isinstance(s, dict) else []
        add_bullets_slide(prs, st, bullets)

out = Path(output)
out.parent.mkdir(parents=True, exist_ok=True)
prs.save(str(out))

print(json.dumps({
    "ok": True,
    "output": str(out),
    "slides": len(prs.slides),
    "title": deck_title,
}))
PYEOF
