import { NextRequest, NextResponse } from 'next/server';
import { verifyInstallToken, packageSkill, getMarketplaceSkill } from '@/lib/marketplace';

/**
 * GET /api/marketplace/skills/:id/install?token=xxx
 *
 * Download a skill package. Requires a valid install token.
 * Returns JSON with skill files that the agent can write to its workspace.
 *
 * Token is verified via HMAC — only tokens generated by our marketplace are accepted.
 * This prevents agents from installing skills from arbitrary sources.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const token = request.nextUrl.searchParams.get('token');

  if (!token) {
    return NextResponse.json(
      { error: 'Missing install token. Get one from the marketplace UI.' },
      { status: 401 }
    );
  }

  // Verify the token
  const payload = verifyInstallToken(token);
  if (!payload) {
    return NextResponse.json(
      { error: 'Invalid or expired install token. Generate a new one from the marketplace.' },
      { status: 403 }
    );
  }

  // Ensure token matches the requested skill
  if (payload.skillId !== id) {
    return NextResponse.json(
      { error: 'Token does not match the requested skill.' },
      { status: 403 }
    );
  }

  // Get skill metadata
  const skill = getMarketplaceSkill(id);
  if (!skill) {
    return NextResponse.json({ error: 'Skill not found' }, { status: 404 });
  }

  // Package the skill files
  const pkg = packageSkill(id);
  if (!pkg) {
    return NextResponse.json(
      { error: 'Skill source not available. This skill may be coming soon.' },
      { status: 404 }
    );
  }

  return NextResponse.json({
    success: true,
    skill: {
      id: skill.id,
      name: skill.name,
      description: skill.description,
      version: skill.version,
      connectionType: skill.connectionType,
    },
    package: pkg,
    instructions: skill.connectionType
      ? `Skill installed. This skill requires a "${skill.connectionType}" connection. Ask your admin to set one up in the Admin Console → Connections.`
      : 'Skill installed successfully. You can start using it right away.',
  });
}
